#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-m := station_focaltech_touch.o
station_focaltech_touch-objs := focaltech_core.o focaltech_ex_fun.o focaltech_ex_mode.o focaltech_flash.o focaltech_gesture.o focaltech_esdcheck.o focaltech_i2c.o focaltech_point_report_check.o focaltech_flash/focaltech_upgrade_ft5452.o focaltech_test/focaltech_test.o focaltech_test/focaltech_test_ini.o focaltech_test/focaltech_test_detail_threshold.o focaltech_test/supported_ic/focaltech_test_ft5452.o


